### ISSUE TITLE
Kotlin Project

### ISSUE THREAD

**Issue by phreed** [jjohannes/gradle-project-setup-howto#1]
I have a Kotlin project.
Do you have an example like `gradle-project-setup-howto` with a `kotlin-plugin` convention?
I tried to modify https://github.com/jjohannes/understanding-gradle/compare/main...phreed:main but it does not seem to be correct.

**Comment by jjohannes** [comment]
Thanks for bringing this up @phreed. I was expecting someone to ask about Kotlin sooner or later. I added it. 😄 

There is a variation of this _how-to_ for Kotlin now: https://github.com/jjohannes/gradle-project-setup-howto/tree/kotlin

This is what I did on top of the Java example: https://github.com/jjohannes/gradle-project-setup-howto/tree/kotlin#kotlin-jvm-projects

Hope this helps! (It's hard to see from the _diff_ you linked, what exactly did not work for you. If you still run into issues, feel free to post it here.)
