### ISSUE TITLE
How to customize the wrapper task in the root plugin

### ISSUE THREAD

**Issue by mqware** [jjohannes/gradle-project-setup-howto#12]
I'd like to customize the wrapper task to download the "all" distribution. The following code from the doc works in the build.gradle.kts file which is in the project root directory, but it doesn't work in the root plugin. Is there a way to make it work in the plugin?
Thanks.

```
tasks.wrapper {
    distributionType = Wrapper.DistributionType.ALL
}
```

**Comment by jjohannes** [comment]
Interesting. This must be a special case in the Kotlin DSL where it fails to provide the `tasks.wrapper` accessor. This works:

```
tasks.named<Wrapper>("wrapper") {
    distributionType = Wrapper.DistributionType.ALL
}
```

(NOTE: It's not really recommended by Gradle to use the ALL distribution. Instead IDEs should download sources on demand. But it's not working well in all scenarios.)

**Comment by mqware** [comment]
Hi Jendrik,

Thanks for providing a solution, I will save it, but I will also take your advice and just stick with the BIN distribution for now.

Cheers,
Peter
