### ISSUE TITLE
Ignore dependency order for injected implementations

### ISSUE THREAD

**Issue by jbaxleyiii** [jjohannes/gradle-project-setup-howto#6]
When using a gradle plugin (internal or external such as detekt) it can sometimes inject implementations at the top of the list. These can 1) have a version and 2) aren't injected in the correct order so the version checking and order checking features of the analysis plugins don't really work.

Is there a way when doing the filtering (https://github.com/jjohannes/gradle-project-setup-howto/blob/87c42549a63e13933e35db960132eda869f632b9/gradle/plugins/dependency-analysis-plugins/src/main/kotlin/org.example.dependency-analysis.gradle.kts#L12-L19) to ignore injected depedencies?

**Comment by jjohannes** [comment]
Yes - you already found the right place to handle such 'special cases'. There is no way, as far as I know, to identify such dependencies automatically. The plugins use the same Gradle API as the build scripts when adding a dependency. You would have to explicitly ignore those dependencies. For example by adding a condition like this:

```
&& !(it is ExternalModuleDependency && it.group == "org.jetbrains.kotlin" && it.name == "kotlin-stdlib")
```
