### ISSUE TITLE
Build Failed Creating `base-plugins.jar`

### ISSUE THREAD

**Issue by phreed** [jjohannes/gradle-project-setup-howto#8]
This is not a problem with the project itself. 
It may be a Gradle problem.
It is probably a Windows 11 vs. Gradle problem. 

The build fails with the following error:
```text
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':platform'.
> java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file C:\Users\feisele\.gradle\caches\jars-9\447ff4e774d837b8b39c9410a295e1b9\base-plugins.jar.
```
When I look in the `C:\Users\feisele\.gradle\caches\jars-9\447ff4e774d837b8b39c9410a295e1b9` folder I see a `base-plugins.jar.lock.lock` file.
Removing this file does not correct the problem.
The suffix on that file seems suspicious to me.

**Comment by jjohannes** [comment]
I keep hearing similar issues with pre-compiled plugins on windows. But I have never come up with a reproducer (not working on WIndows myself) to report something to Gradle.

Would killing all Gradle Daemon processes solve the problem for you?
