### ISSUE TITLE
Provide an example of testing precompiled script plugins using GradleTestKit and ProjectBuilder

### ISSUE THREAD

**Issue by yogurtearl** [jjohannes/gradle-project-setup-howto#9]
Provide examples of testing the precompiled script plugins using [GradleTestKit](https://docs.gradle.org/current/userguide/test_kit.html) and separately using [ProjectBuilder](https://docs.gradle.org/current/javadoc/org/gradle/testfixtures/ProjectBuilder.html), show casing pros/cons of each approach.

**Comment by jjohannes** [comment]
Thanks for the suggestion. This is something I also want to explore and understand better.

**Comment by jjohannes** [comment]
The updated setup now shows how to test using TestKit:
https://github.com/jjohannes/gradle-project-setup-howto#testing-plugins

Thanks again for suggesting to add something in this area.

-----

Regarding TestKit vs. ProjectBuilder: I don't think using ProjectBuilder is very useful when we talk about testing convention plugins. TestKit is closer to the real thing and I think that is what you want to do here: Test your configuration and not "unit test" small pieces of functionality. Therefore, a comparison of both approaches is out of scope of this repo. Maybe it is something to discuss elsewhere (will keep it mind if I should do more content in this area).
ProjectBuilder _might_ be helpful when developing full scale functional plugins to write tests for Gradle types – such as tasks – which are closer to Unit Tests than Function Tests. (But even then, I never use it...)
